### ISSUE TITLE
Airdash/Extra Jump Interaction on Block Edges and Water

### ISSUE THREAD

**Issue by Sequex** [pearuhdox/Cartographer-2.0#30]
Charges do not properly recharge when landing on the edge of a block. In water, you can restore charges when you are above a solid block while submerged, but not while in the water itself. Additionally, Dashing/Extra Jumping can also be done while underwater, but whether or not this is intentional is unclear (though a little silly and could be a bit unwieldy to use, especially as Sprinting is keybound to both dashing and swimming simultaneously).

The system seems to use an 'if block ~ ~-0.2 ~' check, but only uses an 'OnGround:1b' check for triggering the effect; not resetting it. You are also not 'OnGround' if you are in water, and this can extend to climbables such as ladders and vines. The logic might need more finetuning to consider these environments.

Tested using Cloudstep and Windborn as attribute sources, but should presumably still function the same as applying it directly.

**Comment by pearuhdox** [comment]
Will need to think about water interactions and how they should work, but in the meantime, the rest of the issues are bugs.

I'm also marking this as a good first issue as a template for being concise with bugs.

**Comment by pearuhdox** [comment]
Airdash and Extra Jumps will be disabled in water.

**Comment by pearuhdox** [comment]
The specific way that Airdash/Extra Jump triggers is by pressing the valid input keys while not being on the ground *and* being 0.2 blocks above a non-raycastable block (aka air or a pass through able block)

Climable blocks are being extended to blacklist the effect when the player's hitbox is currently within one.

The logic for resetting Extra jump now uses OnGround, with a check before to ensure minimal performance impact, which should resolve the jump triggering when it should not on corners.

The logic for resetting Airdash count is drastically different after some feedback. One Airdash will recharge every 4 seconds. (Regardless of your max amount.)
