### ISSUE TITLE
Mobs with barrage level 10 shoot at twice the expected rate of fire.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#33]
Specifically level 10 gets shot out at the same rate of fire as a player.

**Comment by pearuhdox** [comment]
All levels of Barrage gain speed the more levels there are, which makes them appear exponentially faster. However, the maximum rate of fire has now been set to 1 arrow per 3 ticks for mobs, and 1 per tick for players.
