### ISSUE TITLE
[BUG] Concentration doesn't work on melee attacks.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#44]
Melee attacks don't deal extra damage and the sound only plays every other strike.

**Comment by pearuhdox** [comment]
Needs more information, as I cannot replicate this issue - have requested demonstration of bug via direct message.

**Comment by pearuhdox** [comment]
Tester cannot replicate the issue at this time - likely related to inventory change conditions, will mark closed for now.
