### ISSUE TITLE
[BUG] Correction enchantment redirects blaze fireballs over the player's head.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#45]

**Comment by pearuhdox** [comment]
At this time, it is nice that Correction's code handles fireballs correctly, but specific behavior that is not for bow or crossbow using mobs is not going to be fixed at this time.

This may be handled in the future but currently, the only directly supported mobs for enchantments are Crossbow and Bow using entities.
