### ISSUE TITLE
[BUG] Stacks of items with auto-charge duplicate the stacks at the end of the cooldown

### ISSUE THREAD

**Issue by BeastMasterFTW** [pearuhdox/Cartographer-2.0#47]

**Comment by pearuhdox** [comment]
Set the Max Stack Size of all items in related enchants to 1, as well as their counts on setup and calculation. This happens the first time the item is held by a player, so if not held by the mapmaker, could delete stacks made by players.

For item safety, all of these items should be set to 1 stack size before being modified.
