### ISSUE TITLE
Remap Lightborn to Right Click?

### ISSUE THREAD

**Issue by Sequex** [pearuhdox/Cartographer-2.0#49]
In practice, mapping the ability to place and destroy blocks to the same key is probably not the best idea. It's very easy to accidentally break your placed down torches and they can also get in the way of breaking blocks if you do intend to use the item as a tool (which is pretty contradictory for a tool enchant)

**Comment by pearuhdox** [comment]
This was something I wondered in dev and makes sense, but does require reworking Lightborn to a right click hold enchantment rather than a block click enchantment, which will take time.

**Comment by pearuhdox** [comment]
After playing around with it a bit, the right click mapping causes huge player slowdown which isn't desirable. I've decided to require sneaking to activate Lightborn in the short term. This behavior will be toggleable with a /trigger command for individual players, defaulting on.

Lightborn also considers conventional melee weapons (Swords and Axes) as tools for application - its very possible it will see more use there, but it qualifies more as a tool enchant than a weapon enchantment, hence the category.
