### ISSUE TITLE
[BUG] Crossbows with Repeating and Barrage only shoot barrage on first shot.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#5]
Unequipping and re-equipping the item allows another barrage to be fired, but the enchantment stops working after a single shot.

**Comment by Mad-Science-Matt** [comment]
With more testing it seems that items losing durability can also disable barrage.

**Comment by pearuhdox** [comment]
I am going to relate all issues of enchantments randomly disabling based on inventory swapping to https://github.com/pearuhdox/Cartographer-2.0/issues/7

This is believed to be the root cause of the bug, so I will be closing this issue with a link to the general problem instead.
