### ISSUE TITLE
Barrage Projectile Replacement is bugged with different types of mobs

### ISSUE THREAD

**Issue by SlimeKing77777** [pearuhdox/Cartographer-2.0#54]
So I spawned a drowned wielding a Ricochet V, Barrage V trident and had it attack. The mob worked as intended.

Then I spawned in a blaze wielding a bow with the exact same enchants and things got weird. The blaze shot it's three fireballs which had the ricochet effect but then it attempted to shoot the barrage tridents from the drowned.

I am using a Fabric client with Fabric API and Axiom installed (testing to see if carto works with that), most of the other carto stuff works just fine.

![confused](https://github.com/user-attachments/assets/e033e320-233e-41dc-a03d-34a042490325)

**Comment by pearuhdox** [comment]
Barrage is not supported at this time for any mob that is not a Bow, Crossbow, or Trident user (or more accurately any mob projectile that is not a Trident or Arrow). This support may arrive intentionally but for now this will be marked as wont fix and an enhancement.
