### ISSUE TITLE
[BUG] Attempting to use a trial key with infinity to open a vault wipes your hotbar.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#55]
I was testing to see if trial keys respected the infinity enchantment when I encountered this weird bug. I hope trial keys will support infinity in the release of custom enchantments so that I can give players one key at the start of the map and use vaults to hand out randomized, multiplayer-friendly loot.

**Comment by pearuhdox** [comment]
Trial keys will not be supported for 2 reasons:

Vaults require an exact match of nbt as of 1.21.4. This makes it impractical to support Trial Keys at this time. (Test to verify - Trial Key with infinity enchantment and right clicking with a Vault does not use the key or spawn items from the vault)

Trial Keys do not have an easy to use detection method, requiring use of a retired system to verify that the player used one. This system could be prone to issues at high tps and required a high volume of inventory checks so I will not be using it in the future.
