### ISSUE TITLE
Charon Lexical Advancements need updating to use components

### ISSUE THREAD

**Issue by Sequex** [pearuhdox/Cartographer-2.0#60]
Currently triggering on default inventory_changed conditions, granting the advancement regardless of it being an enabled feature.

Boons: "nbt": "{CartographerAmbrosia:1b}" -> "minecraft:custom_data": {"CartographerAmbrosia":1}
Timepiece: "nbt": "{DeathTimepiece:1b}" -> "minecraft:custom_data": {"DeathTimepiece":1}

**Comment by pearuhdox** [comment]
Fixed in recent commit
