### ISSUE TITLE
[BUG] Ephemeral and Riposte visual effects don't scale with mob size.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#63]
![2024-12-14_22 19 47](https://github.com/user-attachments/assets/7ee1c9a2-f9c5-4899-b5e4-3ae87617a607)

**Comment by pearuhdox** [comment]
This is a code enhancement because adding this is a significantly more complicated feature. Planned for work in the future but not at this time.

**Comment by pearuhdox** [comment]
Closing issue with the re-open label for the future. At the time, this will not be fixed, but I am open to fixing it in the future.
