### ISSUE TITLE
item_name is not a valid property for Throwable, Lunging, and other Consumable Weapons

### ISSUE THREAD

**Issue by SlimeKing77777** [pearuhdox/Cartographer-2.0#64]
Using a throwable item with an item name will "rename" the item to it's default name. Example: When throwing an wooden sword with an item name, it will rename the sword back to "Wooden Sword" when it's on cooldown.

**Comment by pearuhdox** [comment]
If the item has been thrown *before* being named - this behavior is intentional. If it is the first time throwing - this behavior is unintentional.

If the issue is that the item_name field is not supported - that is also unintentional. Currently the custom_name field is supported.

**Comment by pearuhdox** [comment]
Modified the issue - it is the item_name field that is not supported - I've modified the issue to reference this bug going forward so there are no duplicates.

**Comment by pearuhdox** [comment]
Fixed for Throwable as well as Auto Charge, Repeating, and Scavenger
