### ISSUE TITLE
Mobs can no longer use certain carto enchants.

### ISSUE THREAD

**Issue by SlimeKing77777** [pearuhdox/Cartographer-2.0#73]
I think the rewrite for the code broke Throwable and Lunging on mobs.

Tested using this mob: /give @p spawner[block_entity_data={id:"mob_spawner",SpawnCount:1,SpawnRange:4,Delay:0,MinSpawnDelay:600,MaxSpawnDelay:600,MaxNearbyEntities:15,RequiredPlayerRange:16,SpawnPotentials:[{data:{custom_spawn_rules:{sky_light_limit:{min_inclusive:0,max_inclusive:15},block_light_limit:{min_inclusive:0,max_inclusive:15}},entity:{id:"minecraft:skeleton",Health:15f,CustomName:'"Shadowed Eyes"',HandItems:[{id:"minecraft:black_concrete",count:1,components:{"minecraft:attribute_modifiers":[{id:"fca31adf-fa41-453f-82f0-1720eefed18f",type:"attack_damage",amount:2,operation:"add_value",slot:"mainhand"}],"minecraft:enchantments":{levels:{"minecraft:flame":1,"minecraft:power":1,"cartographer_custom_enchantments:weapon/unique/melee/throwable":6}}}},{}],HandDropChances:[0.000F,0.085F],ArmorItems:[{id:"minecraft:leather_boots",count:1,components:{"minecraft:dyed_color":0}},{id:"minecraft:leather_leggings",count:1,components:{"minecraft:dyed_color":0}},{id:"minecraft:leather_chestplate",count:1,components:{"minecraft:dyed_color":0}},{id:"minecraft:player_head",count:1,components:{"minecraft:profile":{id:[I;1779867086,-33339801,-1846853101,2053509928],properties:[{name:"textures",value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGNjZGNlYmNlODc3OWUzOWQxZjFlMWE1YmFjYWI0Njc1YjMxYTliMzE2ZmMzNDQ1OTAzMGE3MjhmM2IyNTdhNCJ9fX0="}]},"minecraft:attribute_modifiers":[{id:"armor",type:"armor",amount:-30,operation:"add_value",slot:"head"},{id:"movement_speed",type:"movement_speed",amount:-0.5,operation:"add_multiplied_base",slot:"head"}]}}],ArmorDropChances:[0.000F,0.000F,0.000F,0.000F],attributes:[{id:"minecraft:max_health",base:15}]}},weight:1}]},item_name='"Shadowed Eyes"',enchantment_glint_override=true,hide_additional_tooltip={}] 1

And this mob: /setblock ~ ~ ~ spawner{SpawnCount:3,SpawnRange:4,Delay:0,MinSpawnDelay:200,MaxSpawnDelay:200,MaxNearbyEntities:10,RequiredPlayerRange:16,SpawnPotentials:[{data:{custom_spawn_rules:{sky_light_limit:{min_inclusive:0,max_inclusive:15},block_light_limit:{min_inclusive:0,max_inclusive:15}},entity:{id:"minecraft:zombie",IsBaby:0b,CustomName:'"Cart2grpher Zombie"',HandItems:[{id:"minecraft:wooden_sword",count:1,components:{"minecraft:enchantments":{levels:{"cartographer_custom_enchantments:weapon/unique/melee/throwable":1}}}},{}],HandDropChances:[0.000F,0.085F],ArmorItems:[{},{},{},{id:"minecraft:cartography_table",count:1,components:{"minecraft:enchantments":{levels:{"cartographer_custom_statuses:passive/nullifying":7}}}}],ArmorDropChances:[0.085F,0.085F,0.085F,0.000F]}},weight:1}]} replace

And this mob: /give @p spawner[block_entity_data={id:"mob_spawner",SpawnCount:3,SpawnRange:4,Delay:0,MinSpawnDelay:600,MaxSpawnDelay:600,MaxNearbyEntities:15,RequiredPlayerRange:16,SpawnPotentials:[{data:{custom_spawn_rules:{sky_light_limit:{min_inclusive:0,max_inclusive:15},block_light_limit:{min_inclusive:0,max_inclusive:15}},entity:{id:"minecraft:spider",Health:15f,CustomName:'"Leaping Spider"',HandItems:[{id:"minecraft:ghast_tear",count:1,components:{"minecraft:item_name":'"Spider\'s Fang"',"minecraft:enchantments":{levels:{"cartographer_custom_enchantments:weapon/unique/melee/lunging":4}}}},{}],HandDropChances:[0.000F,0.085F],attributes:[{id:"minecraft:attack_damage",base:2.5},{id:"minecraft:max_health",base:15},{id:"minecraft:scale",base:1.25}]}},weight:1}]},item_name='"Leaping Spider"',enchantment_glint_override=true,hide_additional_tooltip={}] 1

**Comment by pearuhdox** [comment]
Throwable, Lunging, and Riposte were not checking for player condition on item replacement, hence items being deleted when the mob attempted to use it. This has now been fixed.
