### ISSUE TITLE
[BUG] (Barrage + Flame) only the first arrow in a barrage has the flame enchant.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#76]
Credit to Slimeking for finding this bug.

**Comment by pearuhdox** [comment]
Barrage arrows are not tracking vanilla enchantments atm. I am working on pushing up a fix for this issue.

**Comment by pearuhdox** [comment]
Fixed issue with Power, Flame, and Punch specifically. Punch does not apply on projectile hits that bypass damage, as the system does not deal damage from the arrow directly. Until a knockback system is implemented for interactions like these, this will not be fixed. The level is properly transferring to the arrows though. (Knockback from these hits still applies, it is just not increased by Punch.)
