### ISSUE TITLE
Named items are bugged with Auto Charge and Scavenger

### ISSUE THREAD

**Issue by SlimeKing77777** [pearuhdox/Cartographer-2.0#82]
I used a /give command to give myself an Auto Charge item with an ITEM NAME. The enchantment works but the Item Name is removed and uses the items vanilla name instead.

Tested with this item: `/give @p splash_potion[item_name='{"bold":true,"color":"red","italic":false,"text":"SlimeKing77777\'s Last Mercy"}',potion_contents={potion:"minecraft:strong_healing"},enchantments={levels:{"cartographer_custom_enchantments:weapon/unique/other/auto_charge":1}},custom_data={auto_charge_seconds:15}] 1`

Update, I made a crossbow with scavenger and when the crossbow was given it's arrow, it lost it's name. This happened for both Custom Name and Item Name.

Tested with this item: `/give @p crossbow[item_name='{"bold":true,"color":"red","italic":false,"text":"Solder\'s Spare RPG"}',enchantments={levels:{"cartographer_custom_enchantments:weapon/unique/other/scavenger":1,"minecraft:unbreaking":3,"cartographer_custom_enchantments:weapon/unique/general/explosive":3,"cartographer_custom_enchantments:weapon/unique/general/recoil":10,"cartographer_custom_enchantments:curse/jamming":1}}] 1`

**Comment by pearuhdox** [comment]
Adding a good first issue label to this bug because providing items that are causing issues in bug reports greatly assists in tracking down what is causing those bugs. Thank you for the concise issue!

**Comment by pearuhdox** [comment]
The first item is actually a vanilla bug. Potions do not seem to support item_name properly, or this is an improperly formatted item. Crossbow does seem to be a Cartographer bug.

**Comment by pearuhdox** [comment]
Pushed a fix that should resolve Auto Charge and Scavenger for Crossbows. Item Name does not appear to work with potions regardless, assuming they are supposed to be the same format.

Example of vanilla bug (one of these items will have the set name, and one will not):
`give @p splash_potion[custom_name='"SlimeKing77777\'s Last Mercy"'] 1`
`give @p splash_potion[item_name='"SlimeKing77777\'s Last Mercy"'] 1`
