### ISSUE TITLE
Two Handed can permanently Lock offhands

### ISSUE THREAD

**Issue by Sequex** [pearuhdox/Cartographer-2.0#84]
When a Two Handed item is Locked and offhanded, swapping hands will permanently Lock your swapped item, irreversibly making its effects inaccessible.

Reproduction Steps:
/give @s netherite_sword[enchantments={levels:{"cartographer_custom_enchantments:curse/two_handed":1}}]
/give @s flint[enchantments={levels:{"cartographer_custom_attributes:vanilla/agility":2}}]

1. Equip Flint on offhand
2. Hold Sword (should display Locked at this point)
3. Swap Hands twice
or
1. Equip Sword on offhand
2. Hold Flint (sword should display Locked at this point)
3. Swap Hands (flint is now locked, but sword can be unlocked normally after unequipping flint)

**Comment by pearuhdox** [comment]
I cannot seem to replicate this at the moment. Will reach out for a demonstration ASAP.

**Comment by pearuhdox** [comment]
Closing this for now - pushed a change that should prevent the issue from reappearing.
