### ISSUE TITLE
Attribute Enchants retain effects on Curse of Pride items until reset

### ISSUE THREAD

**Issue by Sequex** [pearuhdox/Cartographer-2.0#85]
/give @s blaze_powder[enchantments={levels:{"cartographer_custom_enchantments:curse/pride":1,"cartographer_custom_attributes:vanilla/celerity":10}}]
For reset (equipping and unequipping resets the attributes):
/give @s flint[enchantments={levels:{"cartographer_custom_attributes:vanilla/agility":2}}]

When equipping an item with Curse of Pride and an attribute enchant (tested with agility, celerity, and cloudstep) will allow its effects to persist even after unequipping (has only been tested with 1 equipped Pride item, not 2).

**Comment by pearuhdox** [comment]
Closing this for now - pushed a change that should prevent the issue from reappearing.
