### ISSUE TITLE
Enchantments that pull a block texture fail when used on bedrock.

### ISSUE THREAD

**Issue by SlimeKing77777** [pearuhdox/Cartographer-2.0#88]
A mob wearing a Quake or Starfall item doesn't activate the enchantments effects. With Quake, it also leaves the marker behind.

I gave Quake 10 leather boots to a skeleton that can pick up items and it didn't work.
I gave Starfall 5 iron boots to a skeleton that can pick up items and it didn't work.

Custom Quake mob: /give @p spawner[item_name='{"color":"gold","text":"Bug Fixed Hoglin"}',hide_additional_tooltip={},enchantment_glint_override=true,block_entity_data={id:"mob_spawner",SpawnCount:1,SpawnRange:4,Delay:0,MinSpawnDelay:1200,MaxSpawnDelay:1200,MaxNearbyEntities:15,RequiredPlayerRange:24,SpawnPotentials:[{data:{custom_spawn_rules:{sky_light_limit:{min_inclusive:0,max_inclusive:15},block_light_limit:{min_inclusive:0,max_inclusive:15}},entity:{id:"minecraft:hoglin",PersistenceRequired:1b,Health:38f,IsImmuneToZombification:1b,CannotBeHunted:1b,CustomName:'{"color":"gold","italic":false,"text":"Bug Fixed Hoglin"}',HandItems:[{id:"minecraft:gold_ingot",count:1,components:{"minecraft:item_name":'"It can use Carto now!"',"minecraft:enchantments":{levels:{"cartographer_custom_enchantments:weapon/unique/melee/slamming":1,"cartographer_custom_enchantments:passive/quake":6}}}},{}],HandDropChances:[0.000F,0.085F],ArmorItems:[{},{},{},{id:"minecraft:gold_nugget",count:1}],ArmorDropChances:[0.085F,0.085F,0.085F,0.000F],attributes:[{id:"minecraft:attack_damage",base:6},{id:"minecraft:max_health",base:38}]}},weight:1}]}] 1

Custom Starfall mob: /give @p spawner[item_name='"Planetoid Specter"',hide_additional_tooltip={},enchantment_glint_override=true,block_entity_data={id:"mob_spawner",SpawnCount:3,SpawnRange:8,Delay:0,MinSpawnDelay:600,MaxSpawnDelay:600,MaxNearbyEntities:15,RequiredPlayerRange:16,SpawnPotentials:[{data:{custom_spawn_rules:{sky_light_limit:{min_inclusive:0,max_inclusive:15},block_light_limit:{min_inclusive:0,max_inclusive:15}},entity:{id:"minecraft:vex",Health:16f,LifeTicks:12000,Passengers:[{id:"minecraft:skeleton",Health:16f,CustomName:'"Planetoid Specter"',HandItems:[{id:"minecraft:bow",count:1},{}],HandDropChances:[0.000F,0.085F],ArmorItems:[{},{},{},{id:"minecraft:oak_sapling",count:1,components:{"minecraft:enchantments":{levels:{"cartographer_custom_enchantments:passive/starfall":6}}}}],ArmorDropChances:[0.085F,0.085F,0.085F,0.000F],attributes:[{id:"minecraft:attack_damage",base:6},{id:"minecraft:max_health",base:16}]}],CustomName:'"Planetoid Specter"',HandItems:[{id:"minecraft:stick",count:1,components:{"minecraft:item_name":'"Stick of Truth"',"minecraft:enchantments":{levels:{"cartographer_custom_enchantments:weapon/unique/melee/throwable":8}}}},{id:"minecraft:oak_sapling",count:1}],HandDropChances:[0.000F,0.000F],attributes:[{id:"minecraft:attack_damage",base:5},{id:"minecraft:max_health",base:16},{id:"minecraft:scale",base:2}]}},weight:1}]}] 1

**Comment by pearuhdox** [comment]
The issue was actually the block getter failing on bedrock. Pushing a fail safe to fix this.
